[agent]
name = "github"
version = "0.0.1"
description = "Github agent that can create, update, and search for repositories and files, as well as view/edit issues and pull requests (depending on the permissions of its access token)"

[options.MODEL_API_KEY]
type = "string"
description = "API key for the model provider"

[options.GITHUB_PERSONAL_ACCESS_TOKEN]
type = "string"
description = "Github token for the service"

[options.MODEL_NAME]
type = "string"
description = "What model to use (e.g 'gpt-4.1')"
default = "x-ai/grok-4-fast:free"

[options.MODEL_BASE_URL]
type = "string"
description = "What model base URL to use (e.g 'https://api.openai.com/v1')"
default = "https://openrouter.ai/api/v1"

[options.MODEL_PROVIDER]
type = "string"
description = "What model provider to use (e.g 'openai', etc)"
default = "openai"

[options.MODEL_MAX_TOKENS]
type = "string"
description = "Max tokens to use"
default = "16000"

[options.MODEL_TEMPERATURE]
type = "string"
description = "What model temperature to use"
default = "0.3"

[options.TIMEOUT_MS]
type = "string"
description = "Connection/tool timeouts in ms"
default = "300"

[runtimes.executable]
command = ["bash", "-c", "./run_agent.sh main.py"]
