# fly.toml app configuration file generated for candidate-deep-research-server on 2025-09-19T18:38:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'candidate-deep-research-server'
primary_region = 'iad'

[build]
  # Ensure these match what your Dockerfile / startup expects
  PORT = "5555"
  REGISTRY_FILE_PATH = "/app/registry.toml"
  # If you add a full config file (config.toml) for Coral
  # CONFIG_FILE_PATH = "/app/config.toml"

[http_service]
  internal_port = 5555
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  app = "bash -lc \"REGISTRY_FILE_PATH=$REGISTRY_FILE_PATH ./gradlew --no-daemon run\""
