# fly.toml app configuration file generated for candidate-deep-research-server on 2025-09-19T18:38:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'candidate-deep-research-server'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 5555
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
