[[local-agent]]
path = "agents/linkedin"

[[local-agent]]
path = "agents/firecrawl"

[[local-agent]]
path = "agents/github"

[[local-agent]]
path = "agents/interface"

[[local-agent]]
path = "agents/person-research"

[[local-agent]]
path = "agents/company-research"
